#
# This file is used by the National Data Catalogue for Semantic Interoperability
#   to harvest the content of this repository and identify all related metadata.
#
#   Information contained here is moreover used to identify and avoid conflicts
#   between assets published by different repositories. This is because
#   a single agency can have different teams publishing via different repositories
#   or different agencies working on the same domains.
#
# Content of this file is validated via pre-commit hooks, that check
#   eg. the existence of the referenced paths.
#
#
version: 0.0.1
name: ontopia
description: "Ontopia public repository"
#
# The default layout will be assets/{asset_type}
#
assets:
  vocabularies:
    path: "./assets/vocabularies"
  ontologies:
    path: "./assets/ontologies"
  schemas:
    path: "./assets/schemas"
