#
# This schema is in OpenAPI 3.0 format
#   and can be referred via #/components/schemas/Person
#
openapi: 3.0.3
info:
  title: The Person schema
  version: 202108.01.00
  description: |-
    This Person schema is derived from the CPV/Person ontology.
paths: {}
servers: []
tags: []
components:
  schemas:
    TaxCode:
      type: string
      x-refersTo: https://w3id.org/italia/onto/CPV/taxCode
      description: Il codice fiscale.
      example: RSSMRA75L01H501A
      maxLength: 16
      minLength: 11
    Parent:
      type: string
      x-refersTo: https://w3id.org/italia/onto/CPV/Person
      description: |-
        Uno schema semplificato per associare il solo URL
        che identifica un genitore.
      additionalProperties: false
      required:
        - href
      properties:
        href:
          type: string
          description: Il codice fiscale del genitore.
          format: uri
    Person:
      type: object
      x-refersTo: https://w3id.org/italia/onto/CPV/Person
      additionalProperties: false
      description: |-
          Questo schema rappresenta una persona fisica.
      required:
      - given_name
      - family_name
      - tax_code
      properties:
        tax_code:
          $ref: "#/components/schemas/TaxCode"
        date_of_birth:
          x-refersTo: https://w3id.org/italia/onto/CPV/dateOfBirth
          format: date
          type: string
        family_name:
          x-refersTo: https://w3id.org/italia/onto/CPV/familyName
          maxLength: 255
          type: string
        given_name:
          x-refersTo: https://w3id.org/italia/onto/CPV/givenName
          maxLength: 255
          type: string
        children:
          x-refersTo: https://w3id.org/italia/onto/CPV/hasChildren
          type: array
          items:
            $ref: "#/components/schemas/Person"
          minItems: 0
          maxItems: 50
        parents:
          x-refersTo: https://w3id.org/italia/onto/CPV/hasParents
          type: array
          items:
            $ref: "#/components/schemas/Parent"
          maxItems: 2
          minItems: 0
